runtime: nodejs
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10


# 위 코드는 구글에서 샘플로 보여주는 app.yaml 파일 예시입니다.
# 그대로 따라 적으면 되겠습니다. 서버의 CPU, 메모리 용량도 셋팅 가능합니다.
# 위 예시는 돈많이 안쓰려고 극 저용량으로 셋팅한 예시입니다.
# (CPU두개에 메모리 4GB는 되어야 보통 사이트를 운영할 만 합니다.)
# 실제 사이트 운영하시려면 맨위 두줄만 적어보셔도 됩니다.
# 구글이 알아서 트래픽에 따라 서버 크기와 사양을 늘려줍니다.

# 다만 instances: 1 이게 아닌 경우 구글이 서버컴퓨터를 여러대 돌리면서 get post요청을 분산처리해줍니다.
# 지금 강의에선 로그인 세션정보를 서버의 램에 저장하고 있는데
# 로그인은 A서버가 처리해줬는데 했었는데 post요청을 B서버가 채어가면 로그인 안되었다고 나오는 경우도 발생할 수 있습니다.
# 그래서 세션데이터를 db나 다른 곳에 저장하는게 안정적으로 서비스가 가능합니다.
# https://github.com/googleapis/nodejs-datastore-session
# 이런거 찾아보셔도 됩니다.


# 2. server.js에 서버를 띄울 때 포트가 8080인지 확인합니다.
# app.listen 이 부분이 8080인지 확인합시다.
# 아니라면 8080으로 변경해줍시다.
# 왜냐면 구글클라우드에서 기본적으로 이용하는 포트가 8080입니다.
# 8080쓰기 싫으시면 따로 설정해주시면 되는데 귀찮으니 8080으로 맞춥니다.